import type { RpcJson } from '../service/rpc-contract.ts';
declare const PACKAGE_NAME = "dsh-capability-resolver";
declare const CANDIDATE_REF = "plugin:dsh-capability-resolver@0.1.0";
declare const ADAPTER_SCHEMA = "dsh-capability-resolver/config@0.1.0";
declare const RANGES: Readonly<{
    readonly freshCacheMs: readonly [1000, 86400000];
    readonly staleCacheMs: readonly [1000, 604800000];
    readonly fetchTimeoutMs: readonly [100, 60000];
    readonly maxCatalogBytes: readonly [65536, 33554432];
    readonly maxCatalogEntries: readonly [1, 20000];
    readonly maxTaskChars: readonly [64, 16000];
    readonly maxResults: readonly [1, 50];
    readonly maxCurrentMatches: readonly [1, 50];
    readonly maxDescriptionChars: readonly [80, 4000];
    readonly maxMatchedTerms: readonly [1, 50];
}>;
/** Secret-free exact settings schema and adapter identity shown in review evidence. */
export declare function pluginConfigurationReview(): Readonly<{
    adapterVersion: string;
    adapterDigest: `sha256:${string}`;
    schemaDigest: `sha256:${string}`;
    schema: readonly Readonly<{
        field: string;
        type: 'integer';
        minimum: number;
        maximum: number;
    }>[];
}>;
/** Strict product-owned configuration accepted for the single P0 Plugin candidate. */
export type CapabilityResolverConfiguration = Readonly<Record<keyof typeof RANGES, number>>;
/** Exact whole-file Profile patch replacement generated by a typed adapter. */
export interface PluginConfigurationPatch {
    readonly packageName: typeof PACKAGE_NAME;
    readonly candidateRef: typeof CANDIDATE_REF;
    readonly schema: typeof ADAPTER_SCHEMA;
    readonly adapterDigest: `sha256:${string}`;
    readonly expectedDigest: `sha256:${string}`;
    readonly nextUtf8: string;
    readonly nextDigest: `sha256:${string}`;
    readonly configuration: CapabilityResolverConfiguration;
}
/** Whether this exact candidate/version has a typed safe configuration adapter. */
export declare function hasPluginConfigurationAdapter(candidateRef: string, version: string): boolean;
/** Build one complete normalized user patch while refusing unowned conflicting rows. */
export declare function buildCapabilityResolverPatch(currentUtf8: string, value: RpcJson): PluginConfigurationPatch;
export {};
//# sourceMappingURL=plugin-config-adapter.d.ts.map
